### ISSUE TITLE
yopass upgrade and browser cache

### ISSUE THREAD

**Issue by PiotrIr** [jhaals/yopass#787]
Hi, I just wonder if you could help me please? 
I've just upgraded yopass to the latest version and the server is working fine. However I can see my browser (and any other user's to which I've sent password) keeps an old version of the website. If I open it in incognito mode - everything is working fine. I'm sure if I will clean cache on my browser - it will start working, but I can't do it on all browsers to which I used to send passwords. Could you advise how to resolve the issue please?

**Comment by jhaals** [comment]
Hi @PiotrIr 

Sorry to hear you're having issues. Yopass uses the create-react-app template which used to include a serviceWorker which where registered with the earlier versions of yopass. My guess is that there's a service worker still active in the browser for your domain. My hope is that it will unregister after some time when it notices that it's no longer present in the website.

You could try opening the console in a "broken" browser when on your installation of yopass and run
```
navigator.serviceWorker.getRegistrations().then((registrations) => { console.log('workers', registrations) })
```
To see if there's a service worker registered

**Comment by PiotrIr** [comment]
Hi jhaals,

Thank you for your reply. Looks you are right about worker:

workers Array [ ServiceWorkerRegistration ]
Promise { <state>: "pending" }

Do you know how long it may take for browser to unregister it? It is four days since I upgraded the yopass and still can see Firefox opens old version...

**Comment by jhaals** [comment]
I don't know how long it takes for it to expire unfortunately.

One workaround could possibly be to add some custom registration logic into to index page. 

```javascript
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })
```

**Comment by PiotrIr** [comment]
Hi Hi jhaals,

Will you be able to advise how to do this? I've tried to log in to container bash and getting message:
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

I'm not good in docker, so any help will be apriciated.

**Comment by jhaals** [comment]
The website is compiled so you cannot change it inside the Docker container, secondly it's running distroless so there's no bash or sh available :) 

The easiest thing you can do is to clone the repository, goto website/public/index.html
and add a script tag like the one below inside the head block and then go back to the root directory that you just cloned and run `docker build -t my-custom-build .` and after that you can run the docker container normally except that you use `my-custom-build` instead of jhaals/yopass when executing the docker run command.
 
```html
<script>
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })
</script>
```

**Comment by grobie** [comment]
For what it's worth, I've had pulled my hair out about this behavior as well back at SoundCloud. The caching results in the page appearing to load just fine, even when it was actually not accessible (because SoundCloud's yopass installation was originally deployed behind a SSO reverse proxy). It also sometimes resulted in a very broken page, when the base html was still cached, but the translations couldn't be fetched.

I basically have no knowledge about browser service workers, but removing/improving the cache behavior would be rad.

**Comment by jhaals** [comment]
Thanks for letting me know.
I'll create a patch to unregister this pesky serviceworker automatically today or early next week.
Sorry for the inconvenience of functionality we where not even using.

**Comment by jhaals** [comment]
So I've just released version 11.1.0 that includes an automatic unregister. I hope that it will make things easier for your @PiotrIr

**Comment by PiotrIr** [comment]
Hi Johan,

Many thanks for this. 
Unfortunately in some reason, after I've upgraded the docker container, this still doesn't work and old website displays. Could you help please?

**Comment by jhaals** [comment]
Hi, does it work if you do a shift+f5 refresh or shift+cmd+r on mac? I had
a service worker installed in my firefox but it got removed using the
latest code and refreshing the page fully.

**Comment by PiotrIr** [comment]
Hi Johan,

Yes, when I pressed ctrl+f5 it has indeed removed all version. Sorry, I've expected it will remove the worker service when I just open the website. Thank you for your help.
